# -*- coding: utf-8 -*-
"""translator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UWDDGRIld-B06ku6pDPbjo28wnHp_ZeZ
"""

import streamlit as st
from googletrans import Translator,LANGUAGES

#  Streamlit app title
st.title("Language Translator")

# text input field  to enter text
input_text = st.text_area("Enter text to translate:")

language = list(LANGUAGES.values())
#  dropdown menu for selecting the target language
target_language = st.selectbox("Select target language:",language)

# function to translate the text
def translate_text(input_text, target_language):
    try:
        translator = Translator()
        translated = translator.translate(input_text, dest=target_language)
        return translated.text
    except Exception as e:
        return f"Error: {str(e)}"

#  button to trigger the translation
if st.button("Translate"):
    if input_text:
        translated_text = translate_text(input_text, target_language)
        st.success(f"Translated text ({target_language}):")
        st.write(translated_text)
    else:
        st.warning("Please enter text to translate.")